spring:
  application:
    name: extract-translate-structure-document
  profiles:
    active: dev

server:
  port: 8083

logging:
  level:
    com.example.documentprocessor: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${app.log-local-dir}/extract-translate-structure-document.log